name: Slack Notification on Main Branch Commit

on:
  push:
    branches:
      - main

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - channel: 'C04JE7MMM1R'
            name: 'biz-solutions'
            webhook: 'SLACK_WEBHOOK_URL'
            message: 'Hello biz-solutions New commit in ${{ github.repository }}'
          - channel: 'C04EV47SVRN'
            name: 'business-team'
            webhook: 'SLACK_WEBHOOK_URLB'
            message: 'Hello business team! Update in ${{ github.repository }}'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ matrix.channel }}
          payload: |
            {
              "text": "${{ matrix.message }}\n\n<${{ github.event.head_commit.url }}|View commit>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets[matrix.webhook] }}
